//! # Software text-buffer rasteriser
//!
//! Converts a [`TextBuffer`] into a flat `&mut [u32]` pixel buffer
//! (format: `0x00RRGGBB`, no alpha channel) suitable for presentation
//! via the `softbuffer` crate.
//!
//! ## When is this used?
//!
//! * As the default renderer on systems without Vulkan support.
//! * When the user explicitly selects "Software" mode (F5).
//! * When the settings GUI overlay is open (the overlay is always
//!   composited in software, even if the main display is Vulkan).
//!
//! ## Font loading
//!
//! The function [`load_or_create_atlas`] attempts to read
//! `assets/font.hex` (a GNU Unifont `.hex` file). If the file is
//! present, full glyph rendering is used with all Unicode BMP
//! characters. If not, a crude "block" fallback font is generated
//! where every printable ASCII character (33-126) is rendered as a
//! solid 6x12 rectangle centered in the 8x16 cell.
//!
//! ## Rendering algorithm
//!
//! For each pixel `(px, py)` in the output:
//!
//! ```text
//! 1. Compute text cell:  cx = px / 8,  cy = py / 16
//! 2. If (cx, cy) is outside the text grid -> output black.
//! 3. Otherwise, fetch the Cell at (cx, cy).
//! 4. Compute intra-cell position:  gx = px % 8,  gy = py % 16
//! 5. Look up the glyph atlas at the cell's codepoint:
//!    atlas_x = (codepoint & 0xFF) * 16 + gx
//!    atlas_y = (codepoint >> 8) * 16 + gy
//! 6. If the atlas pixel is > 128 (foreground): output resolved fg color.
//!    Otherwise: output resolved bg color.
//! ```
//!
//! ## Performance
//!
//! This is a brute-force per-pixel loop with no SIMD or tiling.
//! At 1280x800 (the default window size), it processes ~1M pixels
//! per frame, which takes roughly 2-5 ms on a modern CPU. This is
//! acceptable for 60 fps but would not scale to 4K. For high
//! resolutions, the Vulkan backends are recommended.

use crate::display::TextBuffer;
use crate::display::font::{GlyphAtlas, ATLAS_SIZE, CELL_W, CELL_H};

/// Character cell width in screen pixels.
///
/// Unifont glyphs are 8 pixels wide (narrow) or 16 pixels wide (wide).
/// For text grid purposes, we use 8 pixels per column (wide characters
/// span two columns).
pub const CHAR_W: u32 = 8;

/// Character cell height in screen pixels.
///
/// All Unifont glyphs are 16 pixels tall.
pub const CHAR_H: u32 = 16;

/// Rasterise the text buffer into a pixel slice.
///
/// # Arguments
///
/// * `buffer` - The text buffer to render.
/// * `atlas` - The glyph atlas (loaded or generated by [`load_or_create_atlas`]).
/// * `pixels` - Output pixel buffer. Must have length >= `win_w * win_h`.
///   Pixel format: `0x00RRGGBB` (softbuffer convention, no alpha).
/// * `win_w` - Window width in pixels.
/// * `win_h` - Window height in pixels.
///
/// # Coordinate system
///
/// * `(0, 0)` is the top-left corner of the window.
/// * The text grid starts at `(0, 0)` and extends to
///   `(grid_w * 8 - 1, grid_h * 16 - 1)`.
/// * Pixels outside the text grid are rendered as black.
pub fn render_text_buffer(
    buffer: &TextBuffer,
    atlas: &GlyphAtlas,
    pixels: &mut [u32],
    win_w: u32,
    win_h: u32,
) {
    let grid_w = buffer.width();
    let grid_h = buffer.height();

    for py in 0..win_h {
        let row_off = (py * win_w) as usize;
        for px in 0..win_w {
            let cx = px / CHAR_W;
            let cy = py / CHAR_H;

            let color = if cx < grid_w && cy < grid_h {
                let cell = &buffer.cells()[(cy * grid_w + cx) as usize];
                let fg = cell.foreground.resolve(buffer.palette());
                let bg = cell.background.resolve(buffer.palette());

                let gx = px % CHAR_W;
                let gy = py % CHAR_H;
                let cp = cell.codepoint;

                let acol = cp & 0xFF;
                let arow = (cp >> 8) & 0xFF;
                let ax = (acol * CELL_W + gx) as usize;
                let ay = (arow * CELL_H + gy) as usize;

                let hit = ax < ATLAS_SIZE as usize
                    && ay < ATLAS_SIZE as usize
                    && atlas.pixels[ay * ATLAS_SIZE as usize + ax] > 128;

                if hit { fg } else { bg }
            } else {
                0x000000
            };

            pixels[row_off + px as usize] = color;
        }
    }
}

/// Try to load `assets/font.hex`; fall back to block rectangles.
///
/// # Returns
///
/// A `GlyphAtlas` populated either from the font file or from
/// the fallback generator.
///
/// # Fallback font
///
/// If `assets/font.hex` is not found, generates a minimal font where
/// every printable ASCII character (code points 33 through 126) is
/// rendered as a solid 6x12 pixel rectangle centered in the 8x16 cell.
/// This produces a "everything is a block" appearance that is enough
/// to verify the emulator works but is not useful for reading text.
///
/// The space character (32) is left blank, so backgrounds show through.
pub fn load_or_create_atlas() -> GlyphAtlas {
    if let Ok(data) = std::fs::read_to_string("assets/font.hex") {
        eprintln!("[oc-emu] Loaded font from assets/font.hex ({} bytes)", data.len());
        let mut a = GlyphAtlas::new();
        a.load_hex(&data);
        return a;
    }
    eprintln!("[oc-emu] font.hex not found -- using block fallback");
    let mut a = GlyphAtlas::new();
    for cp in 33u32..=126 {
        let ox = (cp & 0xFF) * CELL_W;
        let oy = ((cp >> 8) & 0xFF) * CELL_H;
        for y in 2..14u32 {
            for x in 1..7u32 {
                a.pixels[((oy + y) * ATLAS_SIZE + ox + x) as usize] = 0xFF;
            }
        }
    }
    a
}