//! # Component subsystem
//!
//! This module defines the component model used by the emulator to
//! mirror OpenComputers' component bus. Each hardware block (GPU,
//! EEPROM, keyboard, screen, filesystem) is represented as a
//! "component" with a unique UUID address and a type name.
//!
//! ## Architecture
//!
//! In OpenComputers, the component bus is an abstraction layer between
//! Lua programs and hardware. Lua code uses `component.list()` to
//! discover available hardware, `component.type(address)` to query
//! what kind of component it is, and `component.invoke(address, method, ...)`
//! to call methods on it.
//!
//! This emulator replicates that model:
//!
//! ```text
//! Lua guest
//!   |
//!   | component.invoke(addr, "set", x, y, text)
//!   v
//! host.rs comp_invoke()
//!   |
//!   | looks up addr in component_types HashMap
//!   | dispatches to the correct Rust handler
//!   v
//! gpu.rs / eeprom.rs / filesystem.rs / etc.
//! ```
//!
//! ## Address generation
//!
//! Each component gets a UUID v4-style address (36 hex characters with
//! dashes). These are generated at runtime using a simple xorshift PRNG
//! seeded from the system clock. They are NOT cryptographically random
//! but are unique enough for component identification.
//!
//! ## Sub-modules
//!
//! * [`gpu`] - Graphics card component (text rendering API)
//! * [`eeprom`] - BIOS storage component
//! * [`keyboard`] - Keyboard input component
//! * [`screen`] - Display screen component
//! * [`filesystem`] - File I/O component

pub mod gpu;
pub mod eeprom;
pub mod keyboard;
pub mod screen;
pub mod filesystem;
pub mod drive;

use std::collections::HashMap;

/// A component address is a UUID v4-formatted string.
///
/// Format: `"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"` (36 characters).
///
/// This is a type alias for `String` rather than a newtype to keep
/// serialisation and Lua interop simple. All component addresses in
/// the system are generated by [`new_address`].
pub type Address = String;

/// Generate a random UUID v4 address for a new component.
///
/// The generated address has the standard UUID format with dashes at
/// positions 8, 12, 16, and 20:
///
/// ```text
/// xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
/// ```
///
/// # Randomness
///
/// Uses a thread-local xorshift64 PRNG seeded from the system clock.
/// This is NOT suitable for cryptographic purposes but provides
/// adequate uniqueness for component addresses within a single
/// emulator session.
///
/// # Thread safety
///
/// Uses `thread_local!` for the PRNG state, so it is safe to call
/// from any thread (though in practice it is only called from the
/// main thread during setup).
///
/// # Returns
///
/// A 36-character `String` in UUID format.
pub fn new_address() -> Address {
    use std::fmt::Write;
    let mut buf = String::with_capacity(36);
    let bytes: [u8; 16] = std::array::from_fn(|_| fastrand_byte());
    for (i, b) in bytes.iter().enumerate() {
        if matches!(i, 4 | 6 | 8 | 10) { buf.push('-'); }
        let _ = write!(buf, "{:02x}", b);
    }
    log::trace!("new component address: {}", buf);
    buf
}

/// Generate a single pseudo-random byte using xorshift64.
///
/// This is a minimal PRNG used only for UUID generation. The state
/// is thread-local and seeded from `SystemTime::now()` on first use.
///
/// # Algorithm
///
/// Xorshift64 with shifts (13, 7, 17). Period: 2^64 - 1.
/// Only the lowest 8 bits of each state are used.
///
/// # Why not `rand` crate?
///
/// To avoid adding a dependency for something this trivial. We only
/// need ~16 bytes of randomness per component, and uniqueness (not
/// unpredictability) is the requirement.
fn fastrand_byte() -> u8 {
    use std::cell::Cell;
    thread_local! {
        static STATE: Cell<u64> = Cell::new(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos() as u64 | 1
        );
    }
    STATE.with(|s| {
        let mut x = s.get();
        x ^= x << 13; x ^= x >> 7; x ^= x << 17;
        s.set(x);
        x as u8
    })
}

/// Public version of fastrand_byte for sound system.
pub fn fastrand_byte_pub() -> u8 {
    fastrand_byte()
}